# Site settings
title: Almeida Painting & Renovations
email: contact@almeidapaintingandrenovations.com
url: https://example.github.io
description: ""
skills: "Painting - Renovations - Touchups"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 34495e #34495e
  primary-rgb: "230, 126, 34" #"230, 126, 34"
  secondary: e67e22 #e67e22
  secondary-dark: 2c3e50 #2c3e50

# Footer settings
footer:
  copyright: Almeida Painting & Renovations
  location: Location
  contact: Contact

# Postal address (add as many lines as necessary)
address:
  - line: Serving Cambridge, Kitchener, Waterloo 
  - line: and surrounding areas for over 20 years.

# Credits content
phone: 
  - line: 1-(519)-242-6124
  - line: contact@almeidapaintingandrenovations.com

# Build settings
markdown: kramdown
permalink: pretty
