# Site settings
title: Almeida Painting & Renovations
email: contact@almeidarenovations.ca
url: https://almeidarenovations.ca
description: ""
skills: "Painting - Renovations - Transformations"
meta_author: Luke Almeida


# Contact form:
# - static : using formspree.io to validate email sending
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 34495e #34495e
  primary-rgb: "52, 73, 94" #"52, 73, 94"
  secondary: A6905F #A6905F
  secondary-dark: 5A4540 #2c3e50

# Footer settings
footer:
  copyright: Almeida Painting & Renovations
  location: Location
  contact: Contact

# Postal address (add as many lines as necessary)
address:
  - line: Serving Cambridge, Kitchener, Waterloo 
  - line: and surrounding areas for over 20 years.

# Credits content
phone: 
  - line: 1-(519)-242-6124
  - line: contact@almeidarenovations.ca

# Build settings
markdown: kramdown
permalink: pretty
